### ISSUE TITLE
What's the best way to configure tests involving heroku connect models for tests on CI /CD flows?

### ISSUE THREAD

**Issue by jeanmw** [thermondo/django-heroku-connect#120]
The approach in the [docs ](https://django-heroku-connect.readthedocs.io/en/stable/test.html) for testing salesforce models works great for me locally, however the schema / tables for heroku connect models are not being created when circleci runs tests. If this isn't too out of scope, what's the best way to ensure that a test database that _isn't_ local correctly creates heroku connect tables? I know the docs state that `The custom database engine will create the Heroku Connect schema for you. The schema is created right via the [pre_migrate](https://docs.djangoproject.com/en/stable/ref/signals/#django.db.models.signals.pre_migrate) signal, only when a test database is created.` but this doesn't seem to apply in this case.

Here's my pytest.yml file:

```
name: Unit Tests
on: [push]
jobs:
  pytest:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: gtm_test_db
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - run: pipx install pipenv
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          cache: 'pipenv'
      - run: pipenv install --dev --deploy
      - name: 'Create env file'
        run: |
          touch .env
          cat .env.example > .env
          cat .env
      - run: pipenv run 
      - run: pipenv run pytest --mccabe --cov=gtm -vv server/gtm
      - run: pipenv run coverage report --fail-under=20
```

pytest.ini

```
[pytest]
DJANGO_SETTINGS_MODULE = gtm.test_settings
python_files = tests.py test_*.py *_tests.py
addopts = -p no:warnings --strict-markers --no-migrations
mccabe-complexity=10
```

I've also tried removing the `--no-migrations` option.

I've tried adding ` - run: pipenv run python server/manage.py create_development_schema`  as a step before pytest runs to the yml file, but as expected there aren't correct permissions to load a schema that way.
